name: OpenSCAP CIS Benchmark

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  
  workflow_dispatch: 

jobs:
  eks-oscap-scan:
    name: OpenScap Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Trigger OSCAP via SSM
      run: |
        aws ssm send-command \
          --instance-ids i-01e01e152f31c9708 \
          --document-name "AWS-RunShellScript" \
          --comment "Run OpenSCAP" \
          --parameters 'commands=[
            "sudo apt install -y libopenscap8",
            "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis-node --report report.html --oval-results ssg-eks-ds.xml || true",
          ]' \
          --timeout-seconds 600 \

    # - name: Upload Report Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: oscap-html-report
    #     path: report.html


    
