name: OpenSCAP EKS CIS Benchmark

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  
  workflow_dispatch: 

jobs:
  eks-oscap-scan:
    name: OpenScap Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: 'us-east-1'

    - name: Trigger OSCAP via SSM
      run: |
        aws ssm send-command \
          --instance-ids i-0ae176e853fc76fcf \
          --document-name "AWS-RunShellScript" \
          --comment "Run OpenSCAP" \
          --parameters 'commands=[
            "sudo yum install -y openscap-scanner scap-security-guide awscli",
          ]' \
          --timeout-seconds 600 \
          --region us-east-1

    # - name: Upload Report Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: oscap-html-report
    #     path: report.html

# "aws s3 cp s3://tuong-backend-bucket/oscap/ssg-alinux2-ds.xml ./ssg-alinux2-ds.xml",
#             "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis-node --report report.html --oval-results ssg-eks-ds.xml || true",
#             "aws s3 cp report.html s3://tuong-backend-bucket/oscap-reports/report-$(date +%s).html"

    
