name: OpenSCAP CIS Benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch: 

jobs:
  build:
    name: OpenScap Scan
    runs-on: self-hosted

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Check current user
      run: whoami

    - name: Run SCAP scan
      run: |
        oscap xccdf eval \
          --profile xccdf_org.ssgproject.content_profile_cis_level1_server \
          --results-arf arf.xml \
          --report report.html \
          --oval-results \
          ssg-ubuntu2204-ds.xml

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: scap-report
        path: report.html
