name: OpenSCAP Runner CIS Benchmark

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  
  workflow_dispatch: 

jobs:
  runner-oscap-scan:
    name: OpenScap Scan
    runs-on: self-hosted

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Run SCAP scan
      run: |
        oscap xccdf eval \
          --profile xccdf_org.ssgproject.content_profile_cis_level1_server \
          --results-arf arf.xml \
          --report report.html \
          --oval-results \
          ssg-ubuntu2204-ds.xml || true 

    - name: Remediate Runner
      run: sudo ansible-playbook -i "localhost," -c local ssg/ansible/ubuntu2204-playbook-cis_level1_server.yml --skip-tags=avahi,demon,cups,isc-dhcp,ldap,rsync,samba,snmp,vsftpd,httpd,nginx,bind,cramfs,usb,sshd_disable_empty_passwords,accounts_user_interactive_home_directory_exists,file_groupownership_home_directories

    - name: Rescan SCAP
      run: |
        oscap xccdf eval \
          --profile xccdf_org.ssgproject.content_profile_cis_level1_server \
          --results-arf arf.xml \
          --report remediated_report.html \
          --oval-results \
          ssg-ubuntu2204-ds.xml || true 
    
    - name: Add Description
      run: python3 description_runner.py

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: scap-report
        path: |
          report.html
          remediated_report.html
          modified_report.html
